// TF2 무기/모자 영어 → 한글 이름 변환 맵
export const TF2_ITEM_NAMES_KR: Record<string, string> = {
  // ===== 금속/화폐 =====
  'Scrap Metal': '고철',
  'Reclaimed Metal': '재생 금속',
  'Refined Metal': '정제 금속',
  'Mann Co. Supply Crate Key': '만코 보급 상자 열쇠',
  'Tour of Duty Ticket': '복무 기록증',
  'Sack of Gems': '보석 더미',
  'Gems': '보석',

  // ===== 스카웃 =====
  'Scattergun': '산탄총',
  'Force-A-Nature': '자연의 힘',
  'Shortstop': '쇼트스탑',
  'Soda Popper': '소다 뚜껑 따개',
  "Baby Face's Blaster": '아기 얼굴 블래스터',
  'Back Scatter': '등 뒤의 산탄',
  'Pistol': '권총',
  'Winger': '윙어',
  "Pretty Boy's Pocket Pistol": '예쁜 남자의 권총',
  'Flying Guillotine': '날아다니는 단두대',
  'Bat': '방망이',
  'Sandman': '샌드맨',
  'Holy Mackerel': '신성한 고등어',
  'Candy Cane': '캔디 케인',
  'Boston Basher': '보스턴 폭행범',
  'Three-Rune Blade': '세 룬의 검',
  'Atomizer': '원자화기',
  'Wrap Assassin': '포장지 암살자',
  "Fan O'War": '전쟁의 부채',

  // ===== 솔저 =====
  'Rocket Launcher': '로켓 발사기',
  'Direct Hit': '직격',
  'Black Box': '블랙 박스',
  'Rocket Jumper': '로켓 점프기',
  'Liberty Launcher': '자유의 발사기',
  'Cow Mangler 5000': '소 분쇄기 5000',
  'Original': '오리지널',
  "Beggar's Bazooka": '거지의 바주카',
  'Air Strike': '공습',
  'Shotgun': '샷건',
  'Buff Banner': '사기 고양 깃발',
  'Gunboats': '건보트',
  "Battalion's Backup": '대대의 지원',
  'Concheror': '정복왕의 소라 껍데기',
  'Shovel': '삽',
  'Equalizer': '평등화기',
  'Pain Train': '고통 열차',
  'Half-Zatoichi': '자토이치의 반검',
  'Disciplinary Action': '징계 조치',
  'Market Gardener': '시장 정원사',
  'Escape Plan': '탈출 계획',
  'Mantreads': '맨트레드',

  // ===== 파이로 =====
  'Flame Thrower': '화염 방사기',
  'Backburner': '후방 버너',
  'Degreaser': '탈지기',
  'Phlogistinator': '플로지스티네이터',
  'Rainblower': '레인블로어',
  "Dragon's Fury": '용의 분노',
  'Flare Gun': '신호탄 권총',
  'Detonator': '기폭 장치',
  'Manmelter': '인간 용해기',
  'Scorch Shot': '그을린 탄환',
  'Thermal Thruster': '열 추진기',
  'Gas Passer': '가스 통과기',
  'Fire Axe': '소방도끼',
  'Axtinguisher': '소화 도끼',
  'Homewrecker': '홈 파괴자',
  'Powerjack': '파워잭',
  'Back Scratcher': '등 긁개',
  'Sharpened Volcano Fragment': '날카로운 화산 파편',
  'Postal Pummeler': '우편 폭격기',
  'Third Degree': '삼도화상',
  'Lollichop': '막대 사탕 도끼',
  'Neon Annihilator': '네온 소멸기',
  'Hot Hand': '뜨거운 손',

  // ===== 데모맨 =====
  'Grenade Launcher': '수류탄 발사기',
  'Loch-n-Load': '록 앤 로드',
  "Ali Baba's Wee Booties": '알리바바의 작은 부츠',
  'Bootlegger': '밀수업자',
  'Loose Cannon': '느슨한 대포',
  'Iron Bomber': '철 폭탄병',
  'Quickiebomb Launcher': '속사 폭탄 발사기',
  'Stickybomb Launcher': '끈끈이 폭탄 발사기',
  'Scottish Resistance': '스코틀랜드 저항군',
  "Chargin' Targe": '돌격 방패',
  'Sticky Jumper': '끈끈이 점퍼',
  'Splendid Screen': '화려한 방패',
  'Tide Turner': '조류 변환기',
  'Bottle': '병',
  'Skullcutter': '해골 절단기',
  'Ullapool Caber': '울라풀 나무',
  'Persian Persuader': '페르시아 설득자',
  "Nessie's Nine Iron": '네시의 9번 아이언',
  'Scottish Handshake': '스코틀랜드식 악수',

  // ===== 헤비 =====
  'Minigun': '미니건',
  'Natascha': '나타샤',
  'Iron Curtain': '철의 장막',
  'Brass Beast': '황동 야수',
  'Tomislav': '토미슬라브',
  'Huo-Long Heater': '훠-롱 히터',
  'Family Business': '가족 사업',
  'Sandvich': '샌드비치',
  'Dalokohs Bar': '달로코스 바',
  'Buffalo Steak Sandvich': '버팔로 스테이크 샌드비치',
  'Second Banana': '두 번째 바나나',
  'Fists': '주먹',
  'Killing Gloves of Boxing': '권투의 살인 장갑',
  'Gloves of Running Urgently': '긴급 달리기 장갑',
  "Warrior's Spirit": '전사의 혼',
  'Fists of Steel': '강철 주먹',
  'Eviction Notice': '퇴거 통지서',
  'Holiday Punch': '휴일 주먹',
  'Bread Bite': '빵 물기',

  // ===== 엔지니어 =====
  'Frontier Justice': '변경의 정의',
  'Widowmaker': '미망인 제조기',
  'Pomson 6000': '폼슨 6000',
  'Rescue Ranger': '구조 수레인저',
  'Panic Attack': '공황 발작',
  'Wrangler': '목동',
  'Gunslinger': '총잡이',
  'Southern Hospitality': '남부의 환대',
  'Jag': '재그',
  'Eureka Effect': '유레카 효과',
  'Golden Wrench': '황금 렌치',
  'Wrench': '렌치',

  // ===== 메딕 =====
  'Syringe Gun': '주사기 총',
  'Blutsauger': '블루트자우거',
  "Crusader's Crossbow": '십자군의 석궁',
  'Overdose': '과용',
  'Medigun': '메디건',
  'Kritzkrieg': '크리츠크리크',
  'Quick-Fix': '빠른 수리',
  'Vaccinator': '예방 접종기',
  'Bonesaw': '뼈 톱',
  'Ubersaw': '우버톱',
  'Vita-Saw': '생명톱',
  'Amputator': '절단기',

  // ===== 스나이퍼 =====
  'Sniper Rifle': '저격 소총',
  'Huntsman': '사냥꾼',
  'Sydney Sleeper': '시드니의 수면제',
  'Bazaar Bargain': '시장 거래',
  'Machina': '마키나',
  "Hitman's Heatmaker": '청부 살인자의 열 제조기',
  'AWPer Hand': 'AWP 손',
  'Fortified Compound': '강화 복합체',
  'Classic': '클래식',
  'SMG': '기관단총',
  "Cleaner's Carbine": '청소부의 카빈',
  'Kukri': '쿠크리',
  "Tribalman's Shiv": '부족민의 칼',
  'Shahanshah': '샤한샤',
  'Bushwacka': '부시와카',

  // ===== 스파이 =====
  'Revolver': '리볼버',
  'Ambassador': '대사',
  'Big Earner': '거물',
  'Enforcer': '집행자',
  'Diamondback': '다이아몬드백',
  'Spy-cicle': '스파이클',
  'Knife': '칼',
  'Kunai': '쿠나이',
  'Your Eternal Reward': '당신의 영원한 보상',
  "Conniver's Kunai": '교활한 쿠나이',
  'Sharp Dresser': '잘 차려입은 자',
  'Wanga Prick': '왕가 찌르기',
  'Black Rose': '검은 장미',
  'Sapper': '공병 기계',
  'Red-Tape Recorder': '붉은 테이프 녹음기',
  'Snack Attack': '간식 공격',
  'Invis Watch': '투명 시계',
  "Cloak and Dagger": '은신과 단도',
  'Dead Ringer': '죽은 자의 종소리',

  // ===== 모자/장식품 =====
  'Modest Pile of Hat': '모자의 소박한 무더기',
  'Team Captain': '팀 캡틴',
  "Soldier's Stash": '병사의 비축',
  "Pyromancer's Mask": '화염술사의 가면',
  'Mining Light': '광부의 등불',
  "Engineer's Cap": '엔지니어 모자',
  "Medic's Mountain Cap": '메딕의 산악 모자',
  'Trophy Belt': '트로피 벨트',
  "Grenadier's Softcap": '척탄병의 소프트캡',
  "Prince Tavish's Crown": '왕자 타비시의 왕관',
  'Familiar Fez': '친숙한 페즈',
  'Prussian Pickelhaube': '프로이센 피켈하우베',
  "Backbiter's Billycock": '뒤통수치기의 빌리콕',
  "Hero's Hachimaki": '영웅의 하치마키',
  'Texas Ten Gallon': '텍사스 텐 갤런',
  "Villain's Veil": '악당의 베일',
  'Merry Weather Cap': '메리 웨더 모자',
  'Glengarry Bonnet': '글렌개리 보닛',
  'Whiskered Gentleman': '구레나룻 신사',
  "Handyman's Handle": '핸디맨의 손잡이',
  'Ye Olde Baker Boy': '옛날 빵장수 소년',
  "Frenchman's Beret": '프랑스인의 베레모',
  'Napoleon Complex': '나폴레옹 콤플렉스',
  "Hustler's Hallmark": '사기꾼의 상표',
  'Attendant': '안내원',
  'Vintage Merryweather': '빈티지 메리웨더',
  "Tippler's Tricorne": '술꾼의 삼각 모자',
  "Copper's Hard Top": '동색 하드탑',
  'Bonk Helm': '봉크 헬멧',
  "Tyrant's Helm": '폭군의 헬멧',
  'Flipped Trilby': '뒤집힌 트릴비',
  'Janissary Ketche': '예니체리 케체',
  'Large Lucowski': '대형 루코브스키',
  'Voodoo Juju': '부두 주술',
  'Pyrobotics Pack': '파이로로봇 팩',
  'Tough Stuff Muffs': '튼튼한 장갑',
  'Dark Falkirk Helm': '어두운 팔커크 헬멧',
  'Antarctic Researcher': '남극 연구원',
  "Combat Medic's Crusher Cap": '전투 메딕의 크러셔 모자',
  "Jumper's Jeepcap": '점퍼의 지프캡',
  'Rimmed Raincatcher': '테두리 빗물받이',
  'Brimstone': '유황',
  "Magistrate's Mullet": '재판관의 멀릿',
  'Anger': '분노',
  "Professional's Panama": '전문가의 파나마',
  "Conjurer's Cowl": '마법사의 두건',
  'Das Metalmeatencasen': '다스 메탈미텐케이슨',
  'Grimm Hatte': '그림 해테',
  "Sober Stuntman's Helmet": '냉정한 스턴트맨 헬멧',
  "Batter's Helmet": '타자의 헬멧',
  "Ol' Snaggletooth": '오래된 덧니',
  "Pyro's Beanie": '파이로의 비니',
  "Safe'n'Sound": '안전과 소리',
  'Dread Knot': '공포의 매듭',
  "Lord Cockswain's Pith Helmet": '콕스웨인 경의 피스 헬멧',
  'Milkman': '우유 배달부',
  "Herald's Helm": '전령의 헬멧',
  'Hard Counter': '강력한 카운터',
  'Ghastly Gibus': '소름 끼치는 기부스',
  'Sniper\'s Snipin\' Glass': '스나이퍼의 저격 유리',
  "Demoman's Fro": '데모맨의 아프로 헤어',
  'Toadstool Topper': '두꺼비버섯 모자',
  "Bill's Hat": '빌의 모자',
  "Max's Severed Head": '맥스의 잘린 머리',
  'Vintage Tyrolean': '빈티지 티롤 모자',
  'Earbuds': '이어버드',
  'Spiral Sallet': '나선형 살레',
  'Pyrovision Goggles': '파이로비전 고글',
  'Powdered Practitioner': '분말 실무자',
  'Summer Shades': '여름 선글라스',
  'Mann Co. Online Cap': '만코 온라인 모자',
  'Clan Pride': '클랜 자부심',
  "Troublemaker's Tossle Cap": '말썽꾼의 토슬 모자',
  'Camera Beard': '카메라 수염',
  'Fishcake': '피시케이크',
  'Balloonicorn': '풍선 유니콘',
  'Flair!': '플레어!',
  'Summer Hat': '여름 모자',
  'Respectless Rubber Glove': '무례한 고무 장갑',
  'Coldfront Curbstompers': '냉전선 발길질',
};

/**
 * TF2 아이템 영어 이름을 한글로 변환
 * 매핑에 없으면 원래 이름 반환
 */
export function getDisplayName(englishName: string): string {
  return TF2_ITEM_NAMES_KR[englishName] || englishName;
}
